name: Deploy para Render

on:
  push:
    branches: [main]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependências e gerar build
        run: |
          cd src
          npm install
          npm run build

      - name: Deploy no Render (Frontend)
        uses: render-actions/deploy@v1
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          directory: frontend

  deploy_backend:
    runs-on: ubuntu-latest
    needs: deploy_frontend
    steps:
      - uses: actions/checkout@v4
      - name: Deploy no Render (Backend)
        uses: render-actions/deploy@v1
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          directory: backend/app